<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630095618 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, position VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, site_id INT DEFAULT NULL, supplier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C62E638F6BD1646 ON contact (site_id)');
        $this->addSql('CREATE INDEX IDX_4C62E6382ADD6D8C ON contact (supplier_id)');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, size VARCHAR(255) NOT NULL, file BYTEA NOT NULL, added_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, site_id INT DEFAULT NULL, supplier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A76F6BD1646 ON document (site_id)');
        $this->addSql('CREATE INDEX IDX_D8698A762ADD6D8C ON document (supplier_id)');
        $this->addSql('CREATE TABLE entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sort SMALLINT DEFAULT NULL, color VARCHAR(10) DEFAULT NULL, theme VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "group" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sort SMALLINT DEFAULT NULL, color VARCHAR(10) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, theme VARCHAR(20) DEFAULT NULL, entity_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6DC044C581257D5D ON "group" (entity_id)');
        $this->addSql('CREATE TABLE site (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, address TEXT DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, site_ref VARCHAR(40) DEFAULT NULL, number_employees INT DEFAULT NULL, recommendations TEXT DEFAULT NULL, comments TEXT DEFAULT NULL, contract_expiration_date VARCHAR(255) DEFAULT NULL, exit_conditions VARCHAR(255) DEFAULT NULL, nb_etp_site VARCHAR(255) DEFAULT NULL, supplier VARCHAR(255) DEFAULT NULL, site_type_id INT DEFAULT NULL, site_criticity_id INT DEFAULT NULL, site_manager_id INT DEFAULT NULL, safety_manager_id INT DEFAULT NULL, entity_id INT DEFAULT NULL, security_manager_id INT DEFAULT NULL, site_category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_694309E43EE86E58 ON site (site_type_id)');
        $this->addSql('CREATE INDEX IDX_694309E41004B534 ON site (site_criticity_id)');
        $this->addSql('CREATE INDEX IDX_694309E45837BBA6 ON site (site_manager_id)');
        $this->addSql('CREATE INDEX IDX_694309E4B20ED089 ON site (safety_manager_id)');
        $this->addSql('CREATE INDEX IDX_694309E481257D5D ON site (entity_id)');
        $this->addSql('CREATE INDEX IDX_694309E4B8ECE616 ON site (security_manager_id)');
        $this->addSql('CREATE INDEX IDX_694309E4F968A252 ON site (site_category_id)');
        $this->addSql('CREATE TABLE site_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE site_criticity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nname VARCHAR(255) DEFAULT NULL, color VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE site_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE suppliers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, executive_name VARCHAR(255) DEFAULT NULL, chief_name VARCHAR(255) DEFAULT NULL, address TEXT DEFAULT NULL, ca_supplier DOUBLE PRECISION DEFAULT NULL, ca_group DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, lastname VARCHAR(255) DEFAULT NULL, firstname VARCHAR(255) DEFAULT NULL, token TEXT DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expired_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E6382ADD6D8C FOREIGN KEY (supplier_id) REFERENCES suppliers (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A762ADD6D8C FOREIGN KEY (supplier_id) REFERENCES suppliers (id)');
        $this->addSql('ALTER TABLE "group" ADD CONSTRAINT FK_6DC044C581257D5D FOREIGN KEY (entity_id) REFERENCES entity (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E43EE86E58 FOREIGN KEY (site_type_id) REFERENCES site_type (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E41004B534 FOREIGN KEY (site_criticity_id) REFERENCES site_criticity (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E45837BBA6 FOREIGN KEY (site_manager_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E4B20ED089 FOREIGN KEY (safety_manager_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E481257D5D FOREIGN KEY (entity_id) REFERENCES entity (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E4B8ECE616 FOREIGN KEY (security_manager_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E4F968A252 FOREIGN KEY (site_category_id) REFERENCES site_category (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E638F6BD1646');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E6382ADD6D8C');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76F6BD1646');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A762ADD6D8C');
        $this->addSql('ALTER TABLE "group" DROP CONSTRAINT FK_6DC044C581257D5D');
        $this->addSql('ALTER TABLE site DROP CONSTRAINT FK_694309E43EE86E58');
        $this->addSql('ALTER TABLE site DROP CONSTRAINT FK_694309E41004B534');
        $this->addSql('ALTER TABLE site DROP CONSTRAINT FK_694309E45837BBA6');
        $this->addSql('ALTER TABLE site DROP CONSTRAINT FK_694309E4B20ED089');
        $this->addSql('ALTER TABLE site DROP CONSTRAINT FK_694309E481257D5D');
        $this->addSql('ALTER TABLE site DROP CONSTRAINT FK_694309E4B8ECE616');
        $this->addSql('ALTER TABLE site DROP CONSTRAINT FK_694309E4F968A252');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE entity');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE site_category');
        $this->addSql('DROP TABLE site_criticity');
        $this->addSql('DROP TABLE site_type');
        $this->addSql('DROP TABLE suppliers');
        $this->addSql('DROP TABLE "user"');
    }
}
