server {
    listen 80;

    server_name localhost;

    root /var/www/html/public;

    location / {
        proxy_pass http://app:5173;
    }

    location /api {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}